const petTypes = [
    {
        species: 'Alpaca',
        youngUntilXMonths: 18,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Ant Farm',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Bird',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Cat',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Dog',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Ferret',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Fish',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Frog or Toad',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Gecko',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Gerbil',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Goat',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Guinea Pig',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Hamster',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Hedgehog',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Hermit Crab',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Horse',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Iguana',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Mantis',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Mouse',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Newt',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Pig',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Rabbit',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Rat',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Salamander',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Sheep',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Snake',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Spider',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Stick-Bugs',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
    {
        species: 'Turtle or Tortoise',
        youngUntilXMonths: 6,
        minInMorning: 30, 
        minInEvening: 30, 
        minInDay: 30, 
        hInWeek: 10, 
        dInMonth: 5, 
        moneyInMonth: 100, 
    },
];